# Generated by Django 4.1.4 on 2022-12-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, upload_to='img/%Y/%m/%d', verbose_name='Изображение')),
            ],
        ),
    ]
