# Generated by Django 4.1.4 on 2022-12-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
