# Generated by Django 4.1.4 on 2022-12-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('phone', models.CharField(max_length=300, verbose_name='Телефон')),
                ('email', models.CharField(max_length=300, verbose_name='Почта')),
                ('agents', models.CharField(max_length=300, verbose_name='Контрагенты')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса')),
            ],
        ),
    ]
