# Generated by Django 4.1.4 on 2022-12-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deliveryaddresses_remove_account_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=300, verbose_name='Адреса'),
            preserve_default=False,
        ),
    ]
