# Generated by Django 4.1.4 on 2022-12-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
