# Generated by Django 4.1.4 on 2022-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userorder_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='total',
            field=models.IntegerField(blank=True, default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
