# Generated by Django 4.1.4 on 2022-12-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='payment_method',
            field=models.CharField(default=1, max_length=300, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='way_get',
            field=models.CharField(default=1, max_length=300, verbose_name='Способ получения'),
            preserve_default=False,
        ),
    ]
