# Generated by Django 4.1.4 on 2022-12-15 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_product_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.availability'),
            preserve_default=False,
        ),
    ]
