# Generated by Django 4.1.4 on 2022-12-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_product_availability_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='name',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='rest',
        ),
        migrations.AddField(
            model_name='availability',
            name='in_stock_rest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остаток в наличии'),
        ),
        migrations.AddField(
            model_name='availability',
            name='on_way_rest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остаток в пути'),
        ),
        migrations.AddField(
            model_name='availability',
            name='remote_rest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остаток в удаленный склад'),
        ),
        migrations.DeleteModel(
            name='AvailabilityName',
        ),
    ]
