# Generated by Django 4.1.4 on 2022-12-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_orderstatus_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы оплаты'},
        ),
        migrations.AddField(
            model_name='userorder',
            name='debt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Задолжность (если есть)'),
        ),
    ]
