# Generated by Django 4.1.4 on 2022-12-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_orderstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productlist'),
        ),
    ]
