# Generated by Django 4.1.5 on 2023-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_productlist_options_remove_productlist_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
