# Generated by Django 4.1.4 on 2022-12-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_one',
        ),
    ]
