# Generated by Django 4.1.4 on 2022-12-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductStatus',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
